# Generated by Django 5.0 on 2024-01-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_pertence'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default=1, help_text='arquivo do documento', upload_to='documentos/'),
            preserve_default=False,
        ),
    ]
